version: '3.4'

services:
  rabbitmqconsumer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80"

  rabbitmqproducer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80"

